spring:
    application:
        name: inspire3_blog
    
    # mariadb
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3307/lgcns_blog
        username: root
        password: root

    # redis refresh token
    data:
        redis:
            host: localhost   # 로컬 개발용
            port: 6379
            password:     # 필요시 설정
            timeout: 6000ms

    jpa:
        hibernate: 
            # create, create-drop, update, none
            ddl-auto: update
        # 콘솔출력
        show-sql: true     
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true 
    h2:
        console:
            enabled: true
            path: /h2-console # http://localhost:8088/h2-console     

server:
    port: 8088 


# token 
jwt:
    secret: Tvhnl3/iJ5RYjJBoFiqUsTGuv+mx0nojz8sfYQ+U3XYFMmltUTTli0S/jT2KzIOv

openApi:
    serviceKey: d0c237c8bd1db1401b390614f15ab29aa1d0815937b0af09698912aa801e31bb
    callBackUrl: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst
    dataType: JSON

openai:
    api-key: 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
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini