spring:
    application:
        name: inspire3_blog

    # ai:
    #     openai:
    #         model: ${OPEN_AI_MODEL}
    #         api:
    #             key: ${OPEN_AI_KEY}
    #             url: ${OPEN_AI_URL}
    
    # mariadb
    # datasource:
    #     driver-class-name: org.mariadb.jdbc.Driver
    #     url: jdbc:mariadb://localhost:3306/LGCNS_blog
    #     username: root
    #     password:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/LGCNS_blog
        username: root
        password: JWT_SECRET_KEY=Tvhnl3/iJ5RYjJBoFiqUsTGuv+mx0nojz8sfYQ+U3XYFMmltUTTli0S/jT2KzIOv

    # h2 db
    # datasource:
    #     driver-class-name:  org.h2.Driver
    #     # url: jdbc:h2:mem:inspire
    #     url: jdbc:h2:file:./data/inspire;AUTO_SERVER=TRUE
    #     username: root
    #     password: 


    # redis refresh token
    data:
        redis:
            host: localhost   # 로컬 개발용
            port: 6379
            password:         # 필요시 설정
            timeout: 6000ms

    jpa:
        hibernate: 
            # create, create-drop, update, none
            ddl-auto:  none 
        # 콘솔출력
        show-sql: true     
        properties:
            hibernate:
                # h2
                # dialect: org.hibernate.dialect.H2Dialect
                # mariadb
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true 
    h2:
        console:
            enabled: true
            path: /h2-console # http://localhost:8088/h2-console     

server:
    port: 8088 


# token 
jwt:
    secret: Tvhnl3/iJ5RYjJBoFiqUsTGuv+mx0nojz8sfYQ+U3XYFMmltUTTli0S/jT2KzIOv

openApi:
    serviceKey: ec1cf84e2c5c58d1ca3e97e41618947d295599a7298f6b7a16f8716b26e9ab60
    callBackUrl: http://apis.data.go.kr/1360000/BeachInfoservice/getVilageFcstBeach
    dataType: JSON

openai:
    api-key: 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
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o-mini